
services:
  postgres_db:
    container_name: postgres_db
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres  # ✅ Assign a network

volumes:
  postgres:

networks:
  postgres:  # ✅ Define the network explicitly
    driver: bridge
