services:
  postgres_db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
#      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
        - postgres
    restart: unless-stopped
volumes:
  postgres:

networks:
  postgres:
